# Generated by Django 5.2.9 on 2026-06-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('contacto', models.CharField(blank=True, default='', help_text='Persona de contacto', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('notas', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('ubicacion', models.CharField(blank=True, default='', help_text='Dirección / ubicación de la obra', max_length=255)),
                ('responsable', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='activa', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
