# Generated by Django 5.2.9 on 2026-07-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_latitud_empresa_longitud_obra_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='entidad',
            field=models.CharField(blank=True, default='', help_text='Estado / entidad federativa', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_exterior',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_interior',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, default='México', max_length=80),
        ),
        migrations.AddField(
            model_name='empresa',
            name='referencias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(blank=True, default='', help_text='Clave SAT del régimen fiscal, ej. 601', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uso_cfdi',
            field=models.CharField(blank=True, default='', help_text='Clave SAT de uso del CFDI, ej. G03', max_length=10),
        ),
        migrations.AddField(
            model_name='obra',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='obra',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='obra',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='obra',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='obra',
            name='entidad',
            field=models.CharField(blank=True, default='', help_text='Estado / entidad federativa', max_length=80),
        ),
        migrations.AddField(
            model_name='obra',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='obra',
            name='numero_exterior',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='obra',
            name='numero_interior',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='obra',
            name='pais',
            field=models.CharField(blank=True, default='México', max_length=80),
        ),
        migrations.AddField(
            model_name='obra',
            name='referencias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección formateada (se arma con las partes de abajo)', max_length=255),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(blank=True, default='', help_text='Dirección formateada (se arma con las partes de abajo)', max_length=255),
        ),
    ]
