# Generated by Django 5.2.17 on 2026-08-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='empresas.empresa'),
        ),
    ]
