# Generated by Django 5.2.9 on 2026-02-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0006_alter_refaccion_options_alter_venta_options_and_more'),
        ('ventas', '0002_alter_venta_options_venta_inventario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemventa',
            options={'ordering': ['id'], 'verbose_name': 'Item de Venta', 'verbose_name_plural': 'Items de Venta'},
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de piezas vendidas'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Se toma automáticamente de la refacción', max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_vendidos', to='refacciones.refaccion'),
        ),
    ]
