# Generated by Django 5.2.9 on 2026-02-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_itemventa_options_alter_itemventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalles de venta'},
        ),
    ]
