# Generated by Django 5.2.9 on 2026-02-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_itemventa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se toma automáticamente de la refacción', max_digits=10),
        ),
    ]
