# Generated by Django 5.2.9 on 2026-07-12 04:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ventas', '0006_alter_itemventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_maquina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de la máquina vendida (IVA incluido)', max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
