# Generated by Django 5.2.9 on 2026-07-14 04:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_backfill_montos_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='aplica_iva',
            field=models.BooleanField(default=False, help_text='Suma IVA (16%) porque el cliente pedirá factura'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_maquina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de la máquina vendida (SIN IVA)', max_digits=12),
        ),
    ]
