# Generated by Django 5.2.9 on 2026-07-15 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
        ('ventas', '0009_venta_aplica_iva_alter_venta_precio_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversiones', to='cotizaciones.cotizacion'),
        ),
    ]
