# Generated by Django 5.2.9 on 2026-07-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='aplica_iva',
            field=models.BooleanField(default=True, help_text='Toda venta lleva IVA (16%) incluido'),
        ),
    ]
