# Generated by Django 5.2.9 on 2026-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_venta_aplica_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
