# Generated by Django 5.2.9 on 2026-08-01 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_cotizacion_cotizacione_estado_831f0a_idx'),
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
        ('inventario', '0012_ordenreparacion_ordenreparacionitem'),
        ('ventas', '0014_venta_cliente_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', '-fecha'], name='ventas_estado_8766e5_idx'),
        ),
    ]
