# Generated by Django 5.2.9 on 2026-08-03 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0024_cotizacion_cotizacione_creada_63682b_idx'),
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
        ('inventario', '0012_ordenreparacion_ordenreparacionitem'),
        ('ventas', '0015_venta_ventas_estado_8766e5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_fecha_b4b2af_idx'),
        ),
    ]
