# Generated by Django 5.2.9 on 2026-08-07 04:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_venta_folio_venta_ventas_fecha_b4b2af_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('notas_cierre', models.CharField(blank=True, max_length=300)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='ventas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de caja',
                'verbose_name_plural': 'Sesiones de caja',
                'db_table': 'sesiones_caja',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('apertura', 'Apertura'), ('venta', 'Venta'), ('devolucion', 'Devolución'), ('entrada', 'Entrada de efectivo'), ('retiro', 'Retiro de efectivo'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], max_length=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=15)),
                ('afecta_efectivo', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='ventas.venta')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas.sesioncaja')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'db_table': 'movimientos_caja',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('usuario',), name='una_sesion_abierta_por_usuario'),
        ),
    ]
