# Generated by Django 5.2.9 on 2026-08-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_caja_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nota_ajuste',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
