# Generated by Django 5.2.9 on 2026-08-09 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0045_configuracionsitio_anticipo_minimo_pct'),
        ('ventas', '0019_venta_nota_ajuste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anticipo_nota',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='venta',
            name='entregada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='entregada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_sobre_pedido', to='maquinaria.equipo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_estimada_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='sobre_pedido',
            field=models.BooleanField(default=False, help_text='Apartado de una máquina sin stock (se manda a pedir; la unidad se asigna al llegar).'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('apartada', 'Apartada'), ('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=12),
        ),
    ]
