# Generated by Django 5.2.9 on 2026-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_venta_anticipo_nota_venta_entregada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pedido_fase',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('en_camino', 'En camino'), ('en_sucursal', 'En sucursal')], default='confirmado', max_length=12),
        ),
    ]
