# Generated by Django 5.2.17 on 2026-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_venta_cliente_venta_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='empresa',
        ),
    ]
