# Generated by Django 5.2.17 on 2026-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_remove_venta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='garantia_proveedor_meses',
            field=models.PositiveSmallIntegerField(default=0, help_text='Meses que el proveedor nos garantiza esta máquina.'),
        ),
        migrations.AddField(
            model_name='venta',
            name='garantia_proveedor_nota',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
