# Generated by Django 5.2.17 on 2026-08-18 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0019_renta_obra_del_padron'),
        ('ventas', '0024_venta_garantia_proveedor_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='renta.renta'),
        ),
    ]
