# Generated by Django 5.2.17 on 2026-08-18 22:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_ordenreparacion_empresa'),
        ('maquinaria', '0050_configuracionsitio_caja_renta_maquinaria_and_more'),
        ('ventas', '0025_movimientocaja_renta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('entregada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maquinaria.equipo')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renglones_venta', to='inventario.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Máquina vendida',
                'verbose_name_plural': 'Máquinas vendidas',
                'db_table': 'venta_maquinas',
                'ordering': ['creada_en', 'id'],
            },
        ),
    ]
