[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "python3 backend/manage.py collectstatic --noinput"
]

[phases.start]
cmds = [
  "gunicorn server.wsgi"
]

