# Generated by Django 5.2.2 on 2026-02-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_add_tipo_to_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-1)', max_digits=4),
        ),
    ]
