# Generated by Django 5.2.2 on 2026-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_category_categoria_rename_orderitem_itemorden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='precio_renta',
            new_name='precio_dia',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
