# Generated by Django 6.0.2 on 2026-02-20 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_inventario_options_inventario_condicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes')], max_length=10)),
                ('duracion', models.PositiveIntegerField(default=1, help_text='Número de unidades según modalidad')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('direccion', models.CharField(help_text='Dirección donde está el equipo durante la renta', max_length=255)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='inventario.inventario')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
                'db_table': 'rentas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
