# Generated by Django 5.2.9 on 2026-02-20 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
