# Generated by Django 5.2.9 on 2026-06-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0002_alter_renta_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='cliente',
            field=models.CharField(blank=True, default='', help_text='Nombre del cliente que renta el equipo', max_length=255),
        ),
        migrations.AddField(
            model_name='renta',
            name='telefono_cliente',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
