# Generated by Django 5.2.9 on 2026-07-12 04:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('renta', '0003_renta_cliente_renta_telefono_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depósito en garantía', max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='renta',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, help_text='Fecha en que realmente se devolvió el equipo', null=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas', to='empresas.obra'),
        ),
        migrations.AddField(
            model_name='renta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de la modalidad al momento de rentar', max_digits=10),
        ),
        migrations.AddField(
            model_name='renta',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo por devolución tardía', max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='renta',
            name='cliente',
            field=models.CharField(blank=True, default='', help_text='Nombre del cliente (si no es una empresa registrada)', max_length=255),
        ),
        migrations.AlterField(
            model_name='renta',
            name='estado',
            field=models.CharField(choices=[('reservada', 'Reservada'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=12),
        ),
    ]
