# Generated by Django 5.2.9 on 2026-07-14 04:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0005_backfill_montos_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='aplica_iva',
            field=models.BooleanField(default=False, help_text='Suma IVA (16%) porque el cliente pedirá factura'),
        ),
        migrations.AddField(
            model_name='renta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
