# Generated by Django 5.2.9 on 2026-07-22 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0006_renta_aplica_iva_renta_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('entrega', 'Al entregar'), ('devolucion', 'Al recibir de vuelta')], max_length=10)),
                ('imagen', models.ImageField(upload_to='rentas/evidencias/')),
                ('nota', models.CharField(blank=True, default='', help_text='Ej. "Rayón en la tapa"', max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='renta.renta')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_renta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de renta',
                'verbose_name_plural': 'Evidencias de renta',
                'db_table': 'renta_evidencias',
                'ordering': ['momento', 'id'],
            },
        ),
    ]
