# Generated by Django 5.2.9 on 2026-07-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0008_renta_entregada_en_renta_entregada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciarenta',
            name='tomada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
