# Generated by Django 5.2.9 on 2026-07-31 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_cotizacion_entrega_prometida'),
        ('renta', '0010_renta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_convertidas', to='cotizaciones.cotizacion'),
        ),
    ]
