# Generated by Django 5.2.9 on 2026-08-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0011_renta_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='token_vinculo',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='token_vinculo_expira',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
