# Generated by Django 5.2.9 on 2026-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0013_renta_rentas_estado_a88338_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='pagos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
