# Generated by Django 5.2.9 on 2026-08-06 20:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0014_renta_pagos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='deposito_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parte del depósito usada para cubrir deuda de renta o daños.', max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='deposito_estado',
            field=models.CharField(choices=[('retenido', 'Retenido'), ('devuelto', 'Devuelto'), ('a_favor', 'A favor del cliente'), ('por_devolver', 'Por devolver'), ('aplicado', 'Aplicado')], default='retenido', max_length=14),
        ),
        migrations.AddField(
            model_name='renta',
            name='deposito_nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='renta',
            name='deposito_reembolso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parte del depósito que se le regresa/acredita al cliente.', max_digits=12),
        ),
        migrations.AddField(
            model_name='renta',
            name='deposito_resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renta',
            name='deposito_resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_resueltos', to=settings.AUTH_USER_MODEL),
        ),
    ]
