# Generated by Django 5.2.9 on 2026-08-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0015_renta_deposito_aplicado_renta_deposito_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='renta_origen',
            field=models.ForeignKey(blank=True, help_text='Renta anterior de la que ésta es continuación (renovación).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='renta.renta'),
        ),
    ]
