# Generated by Django 5.2.17 on 2026-08-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0019_renta_obra_del_padron'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='hora_entrega_estimada',
            field=models.TimeField(blank=True, help_text='Hora aproximada en que se le entrega al cliente. Opcional.', null=True),
        ),
    ]
