# Generated by Django 5.2.17 on 2026-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0020_hora_entrega_estimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='liquidacion_nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
