# Generated by Django 5.2.9 on 2026-02-19 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0002_remove_orden_cupon_remove_verificacionemail_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Refacción',
                'verbose_name_plural': 'Categorías de Refacción',
                'db_table': 'categorias_refaccion',
            },
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_sku', models.CharField(help_text='Código de barras o SKU único', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio al público', max_digits=10)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Costo interno', max_digits=10, null=True)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta cuando baje de esta cantidad')),
                ('ubicacion', models.CharField(blank=True, help_text='Estante, pasillo, etc.', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='refacciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='refacciones.categoriarefaccion')),
                ('maquinas_compatibles', models.ManyToManyField(blank=True, related_name='refacciones_compatibles', to='maquinaria.equipo')),
                ('marcas_compatibles', models.ManyToManyField(blank=True, related_name='refacciones_compatibles', to='maquinaria.marca')),
                ('tipos_compatibles', models.ManyToManyField(blank=True, help_text='Tipos de máquina compatibles (ej. Revolvedoras)', related_name='refacciones_compatibles', to='maquinaria.tipo')),
            ],
            options={
                'verbose_name': 'Refacción',
                'verbose_name_plural': 'Refacciones',
                'db_table': 'refacciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Ajuste)'), ('salida_venta', 'Salida por Venta'), ('salida_taller', 'Uso en Taller'), ('ajuste_negativo', 'Ajuste Negativo (Pérdida)')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='refacciones.refaccion')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
