# Generated by Django 5.2.9 on 2026-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='codigo_sku',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si se deja vacío (REF-0001)', max_length=50, unique=True),
        ),
    ]
