# Generated by Django 5.2.9 on 2026-02-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0002_alter_refaccion_codigo_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriarefaccion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='descripcion',
        ),
    ]
