# Generated by Django 5.2.9 on 2026-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0003_remove_categoriarefaccion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refaccion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='refaccion',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='refaccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='cantidad_stock',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='codigo_sku',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='costo_compra',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='maquinas_compatibles',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='marcas_compatibles',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='tipos_compatibles',
        ),
        migrations.RemoveField(
            model_name='refaccion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='refaccion',
            name='codigo_barras',
            field=models.CharField(blank=True, editable=False, help_text='Código EAN/UPC generado automáticamente', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='refaccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refaccion',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en el taller'),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='refaccion',
            table=None,
        ),
        migrations.DeleteModel(
            name='CategoriaRefaccion',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
