# Generated by Django 5.2.9 on 2026-02-20 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_options_inventario_condicion_and_more'),
        ('refacciones', '0005_alter_refaccion_options_venta_itemventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refaccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Refacción', 'verbose_name_plural': 'Refacciones'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refacciones.refaccion'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_maquinaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VentaItemMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_maquinaria', to='refacciones.venta')),
            ],
            options={
                'verbose_name': 'Item Maquinaria',
                'verbose_name_plural': 'Items Maquinaria',
                'db_table': 'venta_items_maquinaria',
            },
        ),
    ]
