# Generated by Django 5.2.9 on 2026-02-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0006_alter_refaccion_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código EAN/UPC (si ya lo trae, escríbelo; si no, déjalo vacío)', max_length=13, unique=True),
        ),
    ]
