# Generated by Django 5.2.9 on 2026-02-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0007_alter_refaccion_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ventaitemmaquinaria',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventaitemmaquinaria',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='ItemVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaItemMaquinaria',
        ),
    ]
