# Generated by Django 5.2.9 on 2026-07-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0008_remove_venta_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='para_venta',
            field=models.BooleanField(default=False, help_text='Además de mantenimiento, esta refacción también se vende al público'),
        ),
        migrations.AddField(
            model_name='refaccion',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Umbral para alertar reorden (0 = sin alerta)'),
        ),
        migrations.AddField(
            model_name='refaccion',
            name='ubicacion',
            field=models.CharField(blank=True, default='', help_text='Ubicación en el taller (estante/caja)', max_length=120),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras: si la refacción ya lo trae, escríbelo; si no, el sistema genera uno.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='refaccion',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
