# Generated by Django 5.2.9 on 2026-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0009_refaccion_para_venta_refaccion_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Familia para agrupar en la caja (puntas, discos, motor…)', max_length=30),
        ),
    ]
