# Generated by Django 5.2.17 on 2026-08-13 06:14

from django.db import migrations, models


def todas_a_venta(apps, schema_editor):
    # Ahora TODAS las refacciones se venden al público (la caja las vende).
    apps.get_model('refacciones', 'Refaccion').objects.update(para_venta=True)


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0010_refaccion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='para_venta',
            field=models.BooleanField(default=True, help_text='Se vende al público (caja/POS). Todas las refacciones son vendibles; el campo se conserva para el módulo de caja.'),
        ),
        migrations.RunPython(todas_a_venta, migrations.RunPython.noop),
    ]
