# Generated by Django 5.2.17 on 2026-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones', '0011_alter_refaccion_para_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(default=0, help_text='Meses de garantía al comprador. 0 = sin garantía.'),
        ),
    ]
