# Generated by Django 5.2.9 on 2026-07-15 03:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], default='venta', max_length=10)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=40)),
                ('vigencia_dias', models.PositiveIntegerField(default=15, help_text='Días de validez de la cotización')),
                ('aplica_iva', models.BooleanField(default=True, help_text='Suma IVA (16%) al total')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio unitario SIN IVA', max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
            ],
            options={
                'db_table': 'cotizacion_items',
                'ordering': ['id'],
            },
        ),
    ]
