# Generated by Django 5.2.9 on 2026-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_email',
            field=models.EmailField(blank=True, default='', help_text='Correo destino para enviar la cotización', max_length=254),
        ),
    ]
