# Generated by Django 5.2.9 on 2026-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='datos_solicitud',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='origen',
            field=models.CharField(choices=[('admin', 'Creada por el admin'), ('cliente', 'Solicitada por el cliente')], default='admin', max_length=8),
        ),
    ]
