# Generated by Django 5.2.9 on 2026-07-21 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_datos_solicitud_cotizacion_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='atendida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='atendida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='escalada_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se avisó a los respaldos por falta de atención', null=True),
        ),
    ]
