# Generated by Django 5.2.9 on 2026-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_atendida_en_cotizacion_atendida_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionitem',
            name='modalidad',
            field=models.CharField(choices=[('venta', 'Venta'), ('dia', 'Renta por día'), ('semana', 'Renta por semana'), ('mes', 'Renta por mes')], default='venta', max_length=8),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta'), ('mixta', 'Venta y renta')], default='venta', max_length=10),
        ),
    ]
