# Generated by Django 5.2.9 on 2026-07-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_modalidad_datos_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cotizaciones/fotos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cotizaciones.cotizacion')),
            ],
            options={
                'db_table': 'cotizacion_fotos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
