# Generated by Django 5.2.9 on 2026-07-25 05:02
from datetime import timedelta

from django.db import migrations, models


def backfill_vence_el(apps, schema_editor):
    """Calcula vence_el (creación + vigencia) para las cotizaciones existentes."""
    Cotizacion = apps.get_model('cotizaciones', 'Cotizacion')
    for cot in Cotizacion.objects.all().only('id', 'creada', 'vigencia_dias'):
        if cot.creada:
            Cotizacion.objects.filter(pk=cot.pk).update(
                vence_el=cot.creada.date() + timedelta(days=cot.vigencia_dias or 0))


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_cotizacionfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='vence_el',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_vence_el, migrations.RunPython.noop),
    ]
