# Generated by Django 5.2.9 on 2026-07-25 05:18
import secrets

from django.db import migrations, models


def backfill_token(apps, schema_editor):
    """Genera un token único para las cotizaciones que ya existen."""
    Cotizacion = apps.get_model('cotizaciones', 'Cotizacion')
    for pk in Cotizacion.objects.filter(token_publico__isnull=True).values_list('pk', flat=True):
        Cotizacion.objects.filter(pk=pk).update(token_publico=secrets.token_hex(16))


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizacion_vence_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='token_publico',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_token, migrations.RunPython.noop),
    ]
