# Generated by Django 5.2.9 on 2026-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_cotizacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='entrega_prometida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
