# Generated by Django 5.2.9 on 2026-08-01 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_cotizacion_recordatorio_vigencia'),
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', '-creada'], name='cotizacione_estado_831f0a_idx'),
        ),
    ]
