# Generated by Django 5.2.9 on 2026-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_cotizacion_cotizacione_estado_831f0a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='token_vinculo',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='token_vinculo_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
