# Generated by Django 5.2.9 on 2026-08-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_cotizacion_token_vinculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='autorizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='autorizada_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='token_autorizacion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('por_autorizar', 'Por autorizar'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=15),
        ),
    ]
