# Generated by Django 5.2.9 on 2026-08-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_cotizacion_autorizada_en_cotizacion_autorizada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='autorizacion_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
