# Generated by Django 5.2.9 on 2026-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_cotizacion_autorizacion_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cancelacion_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelacion_solicitada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
