# Generated by Django 5.2.9 on 2026-08-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_cotizacion_cancelacion_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('por_autorizar', 'Por autorizar'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=15),
        ),
    ]
