# Generated by Django 5.2.9 on 2026-08-01 17:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0018_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionitem',
            name='precio_lista',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
