# Generated by Django 5.2.9 on 2026-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0021_cotizacionitem_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aceptada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
