# Generated by Django 5.2.9 on 2026-08-03 16:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0022_cotizacion_aceptada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionitem',
            name='duracion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio unitario SIN IVA (por periodo, si es renta)', max_digits=12),
        ),
    ]
