# Generated by Django 5.2.9 on 2026-08-03 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_cotizacionitem_duracion_and_more'),
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['creada'], name='cotizacione_creada_63682b_idx'),
        ),
    ]
