# Generated by Django 5.2.9 on 2026-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0024_cotizacion_cotizacione_creada_63682b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='token_lote',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
