# Generated by Django 5.2.9 on 2026-08-11 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0025_cotizacion_token_lote'),
        ('maquinaria', '0046_cupon_usado_cupon_usado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='maquinaria.cupon'),
        ),
    ]
