# Generated by Django 5.2.17 on 2026-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0027_cotizacion_cliente_cotizacion_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='empresa',
        ),
    ]
