# Generated by Django 5.2.17 on 2026-08-18 21:42

import cotizaciones.models_borrador
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0028_remove_cotizacion_empresa'),
        ('maquinaria', '0050_configuracionsitio_caja_renta_maquinaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_token', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(choices=[('armando', 'Armándola'), ('esperando', 'Esperando autorización'), ('rechazado', 'Rechazado por su autorizador'), ('entregado', 'Ya se mandó a REMALI')], db_index=True, default='armando', max_length=10)),
                ('datos_contacto', models.JSONField(blank=True, default=dict)),
                ('obra', models.JSONField(blank=True, default=dict)),
                ('requiere_factura', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='', max_length=10)),
                ('rechazo_motivo', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores_origen', to='cotizaciones.cotizacion')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores', to='maquinaria.cupon')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrador del cliente',
                'verbose_name_plural': 'Borradores del cliente',
                'db_table': 'cotizacion_borradores',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='BorradorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('duracion', models.PositiveIntegerField(default=1)),
                ('modalidad', models.CharField(default='venta', max_length=8)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('precio_lista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('borrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.borradorcliente')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maquinaria.equipo')),
            ],
            options={
                'db_table': 'cotizacion_borrador_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_token', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('token', models.CharField(default=cotizaciones.models_borrador.nuevo_token, editable=False, max_length=64, unique=True)),
                ('modo', models.CharField(choices=[('opciones', 'Son opciones: autoriza una sola'), ('lista', 'Son varias: autoriza las que quiera')], default='lista', max_length=8)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando al autorizador'), ('resuelto', 'Ya lo resolvió'), ('retirado', 'El cliente lo retiró')], default='pendiente', max_length=10)),
                ('congelado_en', models.DateTimeField(auto_now_add=True)),
                ('vence_el', models.DateField(blank=True, null=True)),
                ('autorizada_por', models.CharField(blank=True, default='', max_length=120)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paquete de autorización',
                'verbose_name_plural': 'Paquetes de autorización',
                'db_table': 'cotizacion_paquetes',
                'ordering': ['-congelado_en'],
            },
        ),
        migrations.AddField(
            model_name='borradorcliente',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borradores', to='cotizaciones.paqueteautorizacion'),
        ),
        migrations.AddConstraint(
            model_name='paqueteautorizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('espacio_token__isnull', True), ('usuario__isnull', False)), models.Q(('espacio_token__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='paquete_un_solo_dueno'),
        ),
        migrations.AddConstraint(
            model_name='borradorcliente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('espacio_token__isnull', True), ('usuario__isnull', False)), models.Q(('espacio_token__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='borrador_un_solo_dueno'),
        ),
    ]
