# Generated by Django 5.2.17 on 2026-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_borradorcliente_borradoritem_paqueteautorizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='autorizacion_rechazo',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='token_autorizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='token_lote',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=15),
        ),
    ]
