# Generated by Django 5.2.17 on 2026-08-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0030_remove_cotizacion_autorizacion_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borradorcliente',
            name='cambios_pedidos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='borradorcliente',
            name='decision',
            field=models.CharField(blank=True, choices=[('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('cambios', 'Le pidieron cambios')], default='', max_length=10),
        ),
    ]
