# Generated by Django 5.2.17 on 2026-08-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0031_borradorcliente_cambios_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteautorizacion',
            name='recordatorio_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
