"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/ 
"""

from pathlib import Path
import os
import importlib
import importlib.util
import dj_database_url

import sys
try:
    import pymysql  # Permite usar PyMySQL como reemplazo de MySQLdb
    pymysql.install_as_MySQLdb()
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps folder to sys.path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# ── Variables de entorno: SE CARGAN AQUÍ, ANTES QUE NADA ───────────────────
#
# Esto vivía más abajo, junto a la configuración de la base, y era un error
# silencioso: SECRET_KEY, DEBUG, ALLOWED_HOSTS y demás se leen unas líneas más
# adelante, así que se evaluaban ANTES de que existieran los archivos .env. En
# la práctica, el DEBUG=True de .env.dev nunca se aplicaba y el proyecto corría
# en local con la configuración de producción sin avisar.
from dotenv import load_dotenv  # noqa: E402

# Base: en Railway estos archivos no existen (git los ignora, no viajan en la
# imagen) y las variables las inyecta la plataforma; load_dotenv no pisa lo que
# ya está en el entorno.
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Y si existe .env.dev, manda: esa es la máquina de alguien desarrollando.
_dev1 = load_dotenv(os.path.join(BASE_DIR.parent, '.env.dev'), override=True)
_dev2 = load_dotenv(os.path.join(BASE_DIR, '.env.dev'), override=True)

# Cargar .env.dev no basta: no define MYSQL_URL, así que no puede sobrescribirlo,
# y la selección de base de más abajo comprueba MYSQL_URL ANTES que las DB_*. El
# MYSQL_URL de producción que vive en .env apunta a mysql.railway.internal, un
# host que solo resuelve dentro de Railway: en local deja el proyecto sin base.
if (_dev1 or _dev2) and os.environ.get('DB_NAME'):
    os.environ.pop('MYSQL_URL', None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)c$-2&1@^51q88$+47^%6egtz$e@5m__u7na^ashnvhl&o^bdp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

def _lista_env(nombre, extra):
    """Lee una lista separada por comas y le suma los valores fijos.

    Filtra vacíos a propósito: `"".split(",")` devuelve `['']`, y una cadena
    vacía colada en CORS_ALLOWED_ORIGINS revienta al arrancar.
    """
    del_entorno = os.environ.get(nombre, "").split(",")
    return [v.strip() for v in del_entorno + extra if v and v.strip()]


ALLOWED_HOSTS = _lista_env("ALLOWED_HOSTS", [
    "remali.up.railway.app",
    "remali.mx",
    "www.remali.mx",
    "localhost",
    "127.0.0.1",
])

CSRF_TRUSTED_ORIGINS = _lista_env("CSRF_TRUSTED_ORIGINS", [
    "https://remali.up.railway.app",
    "https://remali.mx",
    "https://www.remali.mx",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])

# Sitio en construcción: tapa todo el tráfico público con una sola página.
#
# En producción viene ENCENDIDO por defecto, a propósito. La app todavía está a
# medias, y el riesgo no es simétrico: olvidar encenderlo publica un sistema sin
# terminar, mientras que olvidar apagarlo solo deja el aviso un rato de más. El
# valor por defecto debe proteger del error caro.
#
# En local (DEBUG=True) viene apagado, para poder trabajar sin estorbo.
# Para mostrar el sitio real en producción: MODO_CONSTRUCCION=False y redesplegar.
MODO_CONSTRUCCION = os.environ.get(
    "MODO_CONSTRUCCION", "False" if DEBUG else "True"
) == "True"

# Entrar con Google. El client ID es público (viaja en el HTML del botón), por eso
# vive aquí con valor por defecto; el client secret NO se usa en este flujo: el
# navegador recibe un ID token firmado y el backend lo verifica contra las llaves
# públicas de Google. Si algún día se rota el cliente OAuth, basta la variable.
GOOGLE_CLIENT_ID = os.environ.get(
    "GOOGLE_CLIENT_ID",
    "796001180849-nqdgu48bai3retv926fliliebfnscl94.apps.googleusercontent.com",
)


# Application definition

INSTALLED_APPS = [
    # 'daphne' va PRIMERO: reemplaza runserver por su servidor ASGI, para que en
    # local (manage.py runserver) funcionen los WebSockets sin configurar nada más.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'maquinaria',
    'inventario',
    'refacciones',
    'ventas',
    'renta',
    'empresas',
    'facturacion',
    'cotizaciones',
    'asistente',
]


if importlib.util.find_spec('cloudinary') and importlib.util.find_spec('cloudinary_storage'):
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_has_whitenoise = importlib.util.find_spec('whitenoise') is not None
if _has_whitenoise:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Va DESPUÉS del bloque de WhiteNoise para quedar delante de él en la lista.
# Importa: WhiteNoise sirve el index.html del SPA en "/" y corta la cadena ahí,
# así que un middleware colocado más abajo tapa todo el sitio menos la portada,
# que es justo la URL que más se visita.
MIDDLEWARE.insert(1, 'server.construccion.ModoConstruccionMiddleware')


ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR.parent / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'
ASGI_APPLICATION = 'server.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# El entorno ya se cargó arriba del todo, antes de leer SECRET_KEY y DEBUG.
from django.core.exceptions import ImproperlyConfigured

_DB_NAME = os.environ.get('DB_NAME')

if os.environ.get('MYSQL_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('MYSQL_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif _DB_NAME:
    DATABASES = {
        'default': dj_database_url.config(
            default=f'mysql://{os.environ.get("DB_USER", "")}:{os.environ.get("DB_PASSWORD", "")}@{os.environ.get("DB_HOST", "127.0.0.1")}:{os.environ.get("DB_PORT", "3306")}/{_DB_NAME}',
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif os.environ.get('MYSQLDATABASE'):
     DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQLDATABASE'),
            'USER': os.environ.get('MYSQLUSER'),
            'PASSWORD': os.environ.get('MYSQLPASSWORD'),
            'HOST': os.environ.get('MYSQLHOST'),
            'PORT': os.environ.get('MYSQLPORT'),
        }
    }
else:
     DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Esto verifica si la carpeta existe antes de agregarla, evitando que Django explote


WHITENOISE_ROOT = STATIC_ROOT 
WHITENOISE_INDEX_FILE = True




FRONTEND_DIR = os.path.join(BASE_DIR, '..', 'frontend', 'dist')
STATICFILES_DIRS = []
if os.path.exists(FRONTEND_DIR):
    STATICFILES_DIRS.append(FRONTEND_DIR)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}
if _has_whitenoise:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
else:
    STORAGES["staticfiles"] = {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

_cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME')
_api_key = os.environ.get('CLOUDINARY_API_KEY')
_api_secret = os.environ.get('CLOUDINARY_API_SECRET')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _cloud_name,
    'API_KEY': _api_key,
    'API_SECRET': _api_secret,
}

if importlib.util.find_spec('cloudinary') and importlib.util.find_spec('cloudinary_storage'):
    if _cloud_name and _api_key and _api_secret:
        STORAGES['default'] = {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'
        }
        # Ensure cloudinary is configured
        import cloudinary
        cloudinary.config(
            cloud_name=_cloud_name,
            api_key=_api_key,
            api_secret=_api_secret,
            secure=True
        )

REST_FRAMEWORK = {
    # Seguro por defecto: toda vista exige sesión salvo que declare explícitamente
    # AllowAny (login, alta de contacto) o lectura pública vía get_permissions (catálogo).
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Solo se aplica donde la vista lo pide (throttle_classes). Los endpoints
    # públicos sin sesión necesitan techo: cada solicitud de cotización dispara
    # correos a los avisos, así que sin límite es un buzón inundado a un clic.
    'DEFAULT_THROTTLE_RATES': {
        'solicitud_publica': '10/hour',   # cotizaciones que manda un mismo visitante
        'anon_publico': '120/hour',       # navegación anónima del catálogo
        'subida_evidencia': '200/hour',   # fotos de entrega/devolución por técnico
        'login': '10/min',                # intentos de login por IP (anti fuerza bruta)
        'registro': '5/hour',             # altas de cuenta de cliente por IP
        'cambio_password': '10/hour',     # cambios de contraseña propia, por cuenta
    },
}

# JWT: tokens de acceso de larga duración para que la sesión del admin no expire a los 5 min
from datetime import timedelta
SIMPLE_JWT = {
    # Sin esto, entrar con JWT jamás toca last_login y el panel muestra
    # "Nunca ha entrado" para gente que entra a diario.
    'UPDATE_LAST_LOGIN': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# ─────────────────────────────────────────────
#  CACHE — listo para Redis
#  Si REDIS_URL está definido se usa Redis; si no, cache local en memoria.
#  En el futuro, esta misma URL sirve para Celery y Channels.
# ─────────────────────────────────────────────
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    # Sesiones servidas desde cache (Redis) cuando esté disponible
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'remali-locmem',
        }
    }

# Channels: capa de canales para WebSockets (notificaciones en tiempo real).
# Con REDIS_URL usa Redis — necesario en producción con varios workers, para que
# un push llegue al cliente sin importar qué worker atendió su conexión. Sin
# Redis cae a memoria: sirve en local (un proceso) y NO tumba producción, aunque
# ahí el push no cruzaría entre workers (por eso en Railway conviene Redis).
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}
# Para Celery en el futuro: CELERY_BROKER_URL = REDIS_URL

# Estaba en CORS_ALLOW_ALL_ORIGINS = True: cualquier sitio del mundo podía llamar
# a la API desde el navegador de un usuario. En realidad casi no hace falta CORS —
# en producción Django sirve el SPA desde el mismo origen y en desarrollo Vite hace
# de proxy—, así que basta la lista de orígenes propios.
CORS_ALLOWED_ORIGINS = _lista_env("CORS_ALLOWED_ORIGINS", [
    "https://remali.up.railway.app",
    "https://remali.mx",
    "https://www.remali.mx",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
])


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND') or ('django.core.mail.backends.console.EmailBackend' if not os.environ.get('EMAIL_HOST') else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '0') or '0')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0') == '1'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@remali.up.railway.app')




if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://remali.up.railway.app')
    BACKEND_URL = os.environ.get('BACKEND_URL', 'https://remali.up.railway.app')
else:
    FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
    BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000')
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '14400'))
EMAIL_VERIFICATION_TIMEOUT = int(os.environ.get('EMAIL_VERIFICATION_TIMEOUT', '14400'))

if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False

# ─────────────────────────────────────────────
#  Aviso a los respaldos de solicitudes de cotización del cliente
#  Cada solicitud nueva del cliente les llega de INMEDIATO por correo (además de
#  la notificación en el panel) para que puedan contactarlo manualmente.
#  ESCALACION_EMAILS = correos de los respaldos (separados por coma).
# ─────────────────────────────────────────────
ESCALACION_EMAILS = [e.strip() for e in os.environ.get('ESCALACION_EMAILS', '').split(',') if e.strip()]

# ─────────────────────────────────────────────
#  [TEMPORAL · depuración 500 "Mi jornada"] — ELIMINAR al terminar.
#  Solo en DEBUG (local): escribe el traceback COMPLETO de cualquier petición que
#  falle (HTTP 500) a un archivo, para diagnosticar un error que no se reproduce
#  desde aquí. No afecta producción (allá DEBUG=False, este bloque no corre).
# ─────────────────────────────────────────────
if DEBUG:
    _LOG_500_PATH = '/private/tmp/claude-502/-Users-ramses-Developer-Remali--claude-worktrees-happy-perlman-0fa2fb/257c6485-627f-4430-8ed7-a95a9e3ffe46/scratchpad/remali-500.log'
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'detallado_500': {
                'format': '\n===== {asctime} · {levelname} · {name} · {message} =====',
                'style': '{',
            },
        },
        'handlers': {
            'archivo_500': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': _LOG_500_PATH,
                'delay': True,  # no abre el archivo hasta el primer error: no rompe el arranque
                'formatter': 'detallado_500',
            },
        },
        'loggers': {
            # django.request emite ERROR con exc_info=True en cada 500 no manejado.
            'django.request': {'handlers': ['archivo_500'], 'level': 'ERROR', 'propagate': False},
        },
        'root': {'handlers': ['archivo_500'], 'level': 'ERROR'},
    }
