# Generated by Django 5.2.9 on 2026-07-14 03:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_empresa_calle_empresa_ciudad_empresa_codigo_postal_and_more'),
        ('renta', '0005_backfill_montos_renta'),
        ('ventas', '0008_backfill_montos_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], max_length=6)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('regimen_fiscal', models.CharField(blank=True, default='', max_length=10)),
                ('uso_cfdi', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('forma_pago', models.CharField(blank=True, default='', help_text='Clave SAT (01 efectivo, 03 transferencia, 04 tarjeta)', max_length=4)),
                ('concepto', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de facturar'), ('facturada', 'Facturada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('uuid', models.CharField(blank=True, default='', help_text='Folio fiscal del CFDI timbrado', max_length=40)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_factura', to='empresas.empresa')),
                ('renta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_factura', to='renta.renta')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_factura', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Solicitud de factura',
                'verbose_name_plural': 'Solicitudes de factura',
                'db_table': 'solicitudes_factura',
                'ordering': ['-creada'],
            },
        ),
    ]
