# Generated by Django 5.2.17 on 2026-08-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_contacto_cliente'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudfactura',
            name='empresa',
        ),
        migrations.AddField(
            model_name='solicitudfactura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_factura', to='clientes.cliente'),
        ),
    ]
