# Generated by Django 5.2.17 on 2026-08-23 01:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_solicitudfactura_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml', models.TextField(help_text='El CFDI íntegro, tal como llegó. No se edita.')),
                ('uuid', models.CharField(help_text='Folio fiscal', max_length=40, unique=True)),
                ('serie', models.CharField(blank=True, default='', max_length=25)),
                ('folio', models.CharField(blank=True, default='', max_length=40)),
                ('rfc_emisor', models.CharField(blank=True, default='', max_length=20)),
                ('nombre_emisor', models.CharField(blank=True, default='', max_length=200)),
                ('regimen_emisor', models.CharField(blank=True, default='', max_length=10)),
                ('rfc_receptor', models.CharField(blank=True, default='', max_length=20)),
                ('nombre_receptor', models.CharField(blank=True, default='', max_length=200)),
                ('cp_receptor', models.CharField(blank=True, default='', max_length=10)),
                ('regimen_receptor', models.CharField(blank=True, default='', max_length=10)),
                ('uso_cfdi', models.CharField(blank=True, default='', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('moneda', models.CharField(blank=True, default='MXN', max_length=5)),
                ('tipo_comprobante', models.CharField(blank=True, default='', max_length=5)),
                ('forma_pago', models.CharField(blank=True, default='', max_length=5)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=5)),
                ('lugar_expedicion', models.CharField(blank=True, default='', max_length=10)),
                ('fecha_emision', models.CharField(blank=True, default='', max_length=30)),
                ('fecha_certificacion', models.CharField(blank=True, default='', max_length=30)),
                ('sello_cfd', models.TextField(blank=True, default='')),
                ('sello_sat', models.TextField(blank=True, default='')),
                ('no_certificado_emisor', models.CharField(blank=True, default='', max_length=30)),
                ('no_certificado_sat', models.CharField(blank=True, default='', max_length=30)),
                ('rfc_prov_certif', models.CharField(blank=True, default='', max_length=20)),
                ('cadena_original', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('cancelada', 'Cancelada ante el SAT')], default='vigente', max_length=10)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_motivo', models.CharField(blank=True, default='', max_length=255)),
                ('envio_estado', models.CharField(choices=[('pendiente', 'Sin enviar'), ('enviada', 'Enviada'), ('fallo', 'Falló el envío')], default='pendiente', max_length=10)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('envio_error', models.CharField(blank=True, default='', max_length=255)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facturacion.solicitudfactura')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_subidas', to=settings.AUTH_USER_MODEL)),
                ('sustituye_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituida_por', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Factura (CFDI)',
                'verbose_name_plural': 'Facturas (CFDI)',
                'db_table': 'facturas_cfdi',
                'ordering': ['-subida_en'],
            },
        ),
    ]
