# Generated by Django 5.2.17 on 2026-08-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
