# Generated by Django 5.2.17 on 2026-08-17 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, default='', max_length=180)),
                ('numero_exterior', models.CharField(blank=True, default='', max_length=30)),
                ('numero_interior', models.CharField(blank=True, default='', max_length=30)),
                ('colonia', models.CharField(blank=True, default='', max_length=120)),
                ('municipio', models.CharField(blank=True, default='', max_length=120)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('entidad', models.CharField(blank=True, default='', help_text='Estado / entidad federativa', max_length=80)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('pais', models.CharField(blank=True, default='México', max_length=80)),
                ('referencias', models.CharField(blank=True, default='', max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('fisica', 'Persona física'), ('moral', 'Persona moral / empresa')], default='fisica', max_length=6)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('regimen_fiscal', models.CharField(blank=True, default='', help_text='Clave SAT, ej. 601', max_length=10)),
                ('uso_cfdi', models.CharField(blank=True, default='', help_text='Clave SAT, ej. G03', max_length=10)),
                ('cp_fiscal', models.CharField(blank=True, default='', max_length=10)),
                ('email_fiscal', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', help_text='Dirección formateada (se arma con las partes de abajo)', max_length=255)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('requiere_revision', models.BooleanField(db_index=True, default=False)),
                ('revision_motivo', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('puesto', models.CharField(blank=True, default='', max_length=80)),
                ('principal', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto de cliente',
                'verbose_name_plural': 'Contactos de cliente',
                'db_table': 'clientes_contacto',
                'ordering': ['-principal', 'nombre'],
            },
        ),
    ]
