# Generated by Django 5.2.17 on 2026-08-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # La Obra vieja usaba la MISMA tabla ('obras'): esta no puede crearse
    # hasta que aquella se haya borrado.
    dependencies = [
        ('clientes', '0002_alter_contacto_cliente'),
        ('empresas', '0005_muere_empresa_y_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, default='', max_length=180)),
                ('numero_exterior', models.CharField(blank=True, default='', max_length=30)),
                ('numero_interior', models.CharField(blank=True, default='', max_length=30)),
                ('colonia', models.CharField(blank=True, default='', max_length=120)),
                ('municipio', models.CharField(blank=True, default='', max_length=120)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('entidad', models.CharField(blank=True, default='', help_text='Estado / entidad federativa', max_length=80)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('pais', models.CharField(blank=True, default='México', max_length=80)),
                ('referencias', models.CharField(blank=True, default='', max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('nombre', models.CharField(max_length=180)),
                ('responsable', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('ubicacion', models.CharField(blank=True, default='', help_text='Dirección formateada (se arma con las partes de abajo)', max_length=255)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='activa', max_length=12)),
                ('predeterminada', models.BooleanField(default=False, help_text='La que se propone al rentar.')),
                ('notas', models.TextField(blank=True, default='')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
                'ordering': ['-predeterminada', 'nombre'],
                'unique_together': {('cliente', 'nombre')},
            },
        ),
    ]
