# Generated by Django 5.2.17 on 2026-08-18 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_obra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acta', 'Acta constitutiva'), ('ine', 'Identificación oficial'), ('domicilio', 'Comprobante de domicilio'), ('orden_compra', 'Orden de compra'), ('otro', 'Otro')], default='otro', max_length=14)),
                ('archivo', models.FileField(upload_to='clientes/documentos/')),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('vence', models.DateField(blank=True, help_text='Vacío = no caduca.', null=True)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cliente_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del cliente',
                'verbose_name_plural': 'Documentos del cliente',
                'db_table': 'clientes_documento',
                'ordering': ['-subido_en'],
            },
        ),
    ]
