# Generated by Django 5.2.17 on 2026-08-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_documentocliente'),
        ('inventario', '0018_remove_ordenreparacion_empresa'),
        ('ventas', '0024_venta_garantia_proveedor_meses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('inicia', models.DateField()),
                ('meses', models.PositiveSmallIntegerField()),
                ('vence', models.DateField(db_index=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('anulada_motivo', models.CharField(blank=True, default='', max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='clientes.cliente')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='inventario.inventario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'db_table': 'clientes_garantia',
                'ordering': ['-vence'],
            },
        ),
    ]
