# Generated by Django 5.2.9 on 2026-02-19 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0002_remove_orden_cupon_remove_verificacionemail_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('vendido', 'Vendido'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, help_text='Ej: Bodega, Cliente Juan, Taller', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='maquinaria.equipo')),
            ],
        ),
    ]
