# Generated by Django 5.2.9 on 2026-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion_actual',
            field=models.CharField(blank=True, help_text='Ej: Bodega, Cliente Juan, Taller, En renta', max_length=255, null=True),
        ),
    ]
