# Generated by Django 5.2.9 on 2026-02-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion_actual',
            field=models.CharField(blank=True, help_text='Ej: Bodega, Cliente Juan, Taller', max_length=255, null=True),
        ),
    ]
