# Generated by Django 5.2.9 on 2026-02-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_ubicacion_actual'),
        ('maquinaria', '0003_equipo_precio_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Unidad de Maquinaria', 'verbose_name_plural': 'Inventario de Maquinaria'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo (Solo Venta)'), ('seminuevo', 'Seminuevo (Venta y Renta)')], default='nuevo', help_text='Nuevo = solo venta | Seminuevo = venta y renta', max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones internas (daños, detalles, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='maquinaria.equipo', verbose_name='Equipo / Modelo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='numero_serie',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion_actual',
            field=models.CharField(blank=True, help_text='Ej: Bodega, Cliente Juan, Obra, Taller', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
    ]
