# Generated by Django 5.2.9 on 2026-02-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_options_inventario_condicion_and_more'),
        ('maquinaria', '0004_remove_equipo_condicion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='notas',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='condicion',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('seminueva', 'Seminueva')], default='seminueva', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='maquinaria.equipo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('vendido', 'Vendido')], default='disponible', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ubicacion_actual',
            field=models.CharField(default='Bodega', max_length=255),
        ),
        migrations.AlterModelTable(
            name='inventario',
            table=None,
        ),
    ]
