# Generated by Django 5.2.9 on 2026-02-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_options_remove_inventario_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
