# Generated by Django 5.2.9 on 2026-02-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventario_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='notas',
        ),
    ]
