# Generated by Django 5.2.9 on 2026-03-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_inventario_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
