# Generated by Django 5.2.9 on 2026-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_inventario_codigo_alter_inventario_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
