# Generated by Django 5.2.9 on 2026-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_inventario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('mantenimiento', 'Mantenimiento'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
