# Generated by Django 5.2.9 on 2026-07-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventario_estado'),
        ('refacciones', '0009_refaccion_para_venta_refaccion_stock_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.inventario')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones_usadas', to='inventario.mantenimiento')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_mantenimiento', to='refacciones.refaccion')),
            ],
            options={
                'verbose_name': 'Refacción usada',
                'verbose_name_plural': 'Refacciones usadas',
                'db_table': 'mantenimiento_refacciones',
            },
        ),
    ]
