# Generated by Django 5.2.9 on 2026-07-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0011_mantenimiento_mantenimientorefaccion'),
        ('refacciones', '0009_refaccion_para_venta_refaccion_stock_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('cliente', 'Equipo de cliente'), ('interna', 'Máquina propia')], default='cliente', max_length=10)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=40)),
                ('equipo_descripcion', models.CharField(blank=True, default='', help_text='Marca/modelo del equipo del cliente', max_length=255)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=120)),
                ('diagnostico', models.TextField(blank=True, default='', help_text='Falla reportada / diagnóstico')),
                ('trabajo_realizado', models.TextField(blank=True, default='', help_text='Trabajo realizado')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('proceso', 'En proceso'), ('terminada', 'Terminada'), ('entregada', 'Entregada')], default='recibida', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reparacion', to='empresas.empresa')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reparacion', to='inventario.inventario')),
            ],
            options={
                'verbose_name': 'Orden de reparación',
                'verbose_name_plural': 'Órdenes de reparación',
                'db_table': 'ordenes_reparacion',
                'ordering': ['-fecha_recibida'],
            },
        ),
        migrations.CreateModel(
            name='OrdenReparacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('stock', 'De inventario'), ('externa', 'Comprada/pedida aparte')], default='stock', max_length=10)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordenreparacion')),
                ('refaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_reparacion', to='refacciones.refaccion')),
            ],
            options={
                'db_table': 'orden_reparacion_items',
                'ordering': ['id'],
            },
        ),
    ]
