# Generated by Django 5.2.9 on 2026-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_ordenreparacion_token_vinculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='token_publico',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
