# Generated by Django 5.2.9 on 2026-08-07 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_ordenreparacion_token_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='autorizada_para_renta',
            field=models.BooleanField(default=False, help_text='Autoriza rentar esta unidad aunque sea NUEVA. Marcar por: sustitución de unidad dañada, demanda extraordinaria, etc.'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='autorizada_renta_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='autorizada_renta_nota',
            field=models.CharField(blank=True, default='', help_text='Motivo por el cual se autorizó la renta de una unidad nueva.', max_length=255),
        ),
        migrations.AddField(
            model_name='inventario',
            name='autorizada_renta_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
