# Generated by Django 5.2.9 on 2026-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_inventario_autorizada_para_renta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('apartado', 'Apartado'), ('mantenimiento', 'Mantenimiento'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
