# Generated by Django 5.2.17 on 2026-08-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_contacto_cliente'),
        ('inventario', '0016_alter_inventario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='clientes.contacto'),
        ),
    ]
