# Generated by Django 5.2.9 on 2026-02-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cupon',
        ),
        migrations.RemoveField(
            model_name='verificacionemail',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='VerificacionEmail',
        ),
    ]
