# Generated by Django 5.2.9 on 2026-02-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0002_remove_orden_cupon_remove_verificacionemail_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo de venta en MXN (ej: 85000.00)', max_digits=12, null=True),
        ),
    ]
