# Generated by Django 5.2.9 on 2026-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0003_equipo_precio_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='disponible_renta',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='disponible_venta',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='estado',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo de venta en MXN', max_digits=12, null=True),
        ),
    ]
