# Generated by Django 5.2.9 on 2026-02-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0004_remove_equipo_condicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
