# Generated by Django 5.2.2 on 2026-02-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0004_alter_cupon_descuento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cupon',
            table='cupones',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemOrden',
        ),
        migrations.AlterModelTable(
            name='itemorden',
            table='items_orden',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Orden',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='ordenes',
        ),
        migrations.RenameModel(
            old_name='EmailVerification',
            new_name='VerificacionEmail',
        ),
        migrations.AlterModelTable(
            name='verificacionemail',
            table='verificaciones_email',
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='tipos',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marcas',
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='equipos',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='itemorden',
            old_name='order',
            new_name='orden',
        ),
        migrations.RenameField(
            model_name='itemorden',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='coupon',
            new_name='cupon',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='verificacionemail',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='verificacionemail',
            old_name='used',
            new_name='usado',
        ),
        migrations.RenameField(
            model_name='verificacionemail',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='products/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='maquinaria.equipo')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'imagenes_producto',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
