# Generated by Django 5.2.9 on 2026-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0006_rename_precio_renta_equipo_precio_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='condicion',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('seminuevo', 'Seminuevo')], default='seminuevo', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('vendido', 'Vendido')], default='disponible', max_length=10),
        ),
    ]
