# Generated by Django 5.2.9 on 2026-06-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0006_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('renta', 'Renta'), ('venta', 'Venta'), ('alerta', 'Alerta'), ('inventario', 'Inventario'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('seccion', models.CharField(blank=True, default='', max_length=40)),
                ('leida', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creada'],
            },
        ),
    ]
