# Generated by Django 5.2.9 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

