# Generated by Django 5.2.9 on 2026-06-05 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0008_notificacion_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('asunto', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('last_read_admin', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación (soporte)',
                'verbose_name_plural': 'Conversaciones (soporte)',
                'db_table': 'conversaciones_soporte',
                'ordering': ['-actualizada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_tipo', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], max_length=20)),
                ('cuerpo', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('autor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='maquinaria.conversacionsoporte')),
            ],
            options={
                'verbose_name': 'Mensaje (soporte)',
                'verbose_name_plural': 'Mensajes (soporte)',
                'db_table': 'mensajes_soporte',
                'ordering': ['creada', 'id'],
            },
        ),
    ]
