# Generated by Django 5.2.9 on 2026-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0010_alter_cupon_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='', max_length=120),
        ),
    ]
