# Generated by Django 5.2.9 on 2026-07-21 21:56

import django.core.validators
import maquinaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0011_alter_equipo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ficha_tecnica',
            field=models.FileField(blank=True, help_text='PDF de ficha técnica del equipo (opcional)', null=True, storage=maquinaria.models.select_ficha_storage, upload_to='fichas/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
