# Generated by Django 5.2.9 on 2026-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0012_equipo_ficha_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='especificaciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
