# Generated by Django 5.2.9 on 2026-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0013_equipo_especificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_principal', models.CharField(blank=True, default='', help_text='Número que ve el cliente en la tienda (10 dígitos)', max_length=20)),
                ('whatsapp_respaldos', models.JSONField(blank=True, default=list, help_text='Respaldos: [{"label": "Respaldo 1", "number": "7441234567"}]')),
                ('negocio_nombre', models.CharField(blank=True, default='REMALI', max_length=120)),
                ('negocio_telefono', models.CharField(blank=True, default='', max_length=40)),
                ('negocio_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('negocio_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('negocio_footer', models.CharField(blank=True, default='¡Gracias por su preferencia!', max_length=200)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
                'db_table': 'configuracion_sitio',
            },
        ),
        migrations.CreateModel(
            name='CorreoAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('etiqueta', models.CharField(blank=True, default='', help_text='Ej. "Respaldo 1"', max_length=60)),
                ('verificado', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Correo de aviso',
                'verbose_name_plural': 'Correos de aviso',
                'db_table': 'correos_aviso',
                'ordering': ['email'],
            },
        ),
    ]
