# Generated by Django 5.2.9 on 2026-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0015_rol_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empresa',
            field=models.CharField(blank=True, default='', help_text='Empresa para la que trabaja el cliente (declarada por él)', max_length=180),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='obra_direccion',
            field=models.CharField(blank=True, default='', help_text='Dónde se entrega la maquinaria', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='obra_responsable',
            field=models.CharField(blank=True, default='', help_text='Quién recibe en la obra', max_length=180),
        ),
    ]
