# Generated by Django 5.2.9 on 2026-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0016_perfilusuario_empresa_perfilusuario_obra_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones',
            field=models.TextField(blank=True, default='Anticipo del 60% para iniciar el pedido; el resto contra entrega.\nPago de contado: 5% de descuento.', help_text='Condiciones de pago que aparecen en la cotización'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='datos_bancarios',
            field=models.TextField(blank=True, default='', help_text='Datos para depósito/transferencia que se muestran en la cotización (banco, titular, cuenta, CLABE)'),
        ),
    ]
