# Generated by Django 5.2.9 on 2026-07-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0017_configuracionsitio_cotizacion_condiciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='cotizacion_cierre',
            field=models.TextField(blank=True, default='En espera de que lo anterior merezca su conformidad y nos veamos favorecidos con su apreciable compra, lo saludamos afectuosamente.', help_text='Frase de despedida al pie de la cotización'),
        ),
    ]
