# Generated by Django 5.2.9 on 2026-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0018_configuracionsitio_cotizacion_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='negocio_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='negocio_representante',
            field=models.CharField(blank=True, default='', help_text='Nombre que firma la cotización (ej. C.P. Nombre Apellido)', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='negocio_web',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
