# Generated by Django 5.2.9 on 2026-07-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0019_configuracionsitio_negocio_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones',
            field=models.TextField(blank=True, default='Anticipo del 60% para iniciar el pedido; el resto contra entrega.\nPago de contado (una sola exhibición): 5% de descuento.\nPrecios sujetos a cambio sin previo aviso.', help_text='Condiciones de pago que aparecen en la cotización'),
        ),
    ]
