# Generated by Django 5.2.9 on 2026-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0020_alter_configuracionsitio_cotizacion_condiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_cierre',
            field=models.TextField(blank=True, default='Confiando en que lo anterior sea de su agrado y esperando contar con su valiosa preferencia, le extendemos un cordial saludo.', help_text='Frase de despedida al pie de la cotización'),
        ),
    ]
