# Generated by Django 5.2.9 on 2026-07-26 17:48

from django.db import migrations, models


def backfill_condicion(apps, schema_editor):
    """Deduce la condición de cada equipo por sus unidades de inventario:
    si la mitad o más son seminuevas, el equipo es seminuevo (renta); si no,
    nuevo (venta). Sin unidades queda 'nueva' por default. El admin lo ajusta."""
    Equipo = apps.get_model('maquinaria', 'Equipo')
    for eq in Equipo.objects.all():
        unidades = list(eq.unidades.all())
        if not unidades:
            continue
        semis = sum(1 for u in unidades if getattr(u, 'condicion', '') == 'seminueva')
        if semis * 2 >= len(unidades):
            eq.condicion = 'seminueva'
            eq.save(update_fields=['condicion'])


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0022_cupon_creado_cupon_motivo_cupon_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='condicion',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('seminueva', 'Seminueva')], default='nueva', max_length=10),
        ),
        migrations.RunPython(backfill_condicion, migrations.RunPython.noop),
    ]
