# Generated by Django 5.2.9 on 2026-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0023_equipo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones_renta',
            field=models.TextField(blank=True, default='IMPORTANTE\nEl equipo deberá entregarse en las mismas condiciones en que se recibe (limpio); de lo contrario se hará un cargo adicional de $300.00 más IVA.\nDiariamente y antes de arrancar el motor, verificar el nivel de aceite y agregar en caso necesario.\nHacer cambio de aceite cada 25 horas de trabajo.\nUtilizar gasolina limpia en los motores.\nNo desarmar parcial ni totalmente ningún equipo sin autorización de nuestra gerencia de servicio; reportar cualquier desperfecto a los tels. 744-507-33-34 / 744-373-72-01.\nEn caso de no atender lo anterior, o de avería y daños en la máquina, la reparación será por cuenta del cliente.', help_text='Condiciones que aparecen en las cotizaciones de RENTA'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones',
            field=models.TextField(blank=True, default='Anticipo del 60% para iniciar el pedido; el resto contra entrega.\nPago de contado (una sola exhibición): 5% de descuento.\nPrecios sujetos a cambio sin previo aviso.', help_text='Condiciones que aparecen en las cotizaciones de VENTA'),
        ),
    ]
