# Generated by Django 5.2.9 on 2026-07-26 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0024_cotizacion_condiciones_renta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Alias para identificarla (ej. "Torre Costera")', max_length=120)),
                ('responsable', models.CharField(blank=True, default='', max_length=180)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra de cliente',
                'verbose_name_plural': 'Obras de cliente',
                'db_table': 'obras_cliente',
                'ordering': ['nombre'],
            },
        ),
    ]
