# Generated by Django 5.2.9 on 2026-07-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0025_obra_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='que_incluye',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
