# Generated by Django 5.2.9 on 2026-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0026_equipo_que_incluye'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='promo_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
