# Generated by Django 5.2.9 on 2026-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0027_equipo_promo_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelloTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=30, unique=True)),
                ('marca', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
