# Generated by Django 5.2.9 on 2026-08-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0028_sellotema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajesoporte',
            name='conversacion',
        ),
        migrations.RemoveField(
            model_name='mensajesoporte',
            name='autor_admin',
        ),
        migrations.DeleteModel(
            name='ConversacionSoporte',
        ),
        migrations.DeleteModel(
            name='MensajeSoporte',
        ),
    ]
