# Generated by Django 5.2.9 on 2026-08-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0032_nombres_propios_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_cp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_razon_social',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_regimen',
            field=models.CharField(blank=True, default='', help_text='Clave SAT, ej. 601, 612, 626', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_rfc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fiscal_uso_cfdi',
            field=models.CharField(blank=True, default='', help_text='Clave SAT, ej. G03, P01', max_length=10),
        ),
    ]
