# Generated by Django 5.2.9 on 2026-08-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0033_perfilusuario_fiscal_cp_perfilusuario_fiscal_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obracliente',
            options={'ordering': ['-predeterminada', 'nombre'], 'verbose_name': 'Obra de cliente', 'verbose_name_plural': 'Obras de cliente'},
        ),
        migrations.AddField(
            model_name='obracliente',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
    ]
