# Generated by Django 5.2.9 on 2026-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0035_obras_predeterminadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='dias_entrega_pedido',
            field=models.PositiveIntegerField(default=0, help_text='Días estimados de entrega para ventas sobre pedido (respaldo general).'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='dias_entrega_pedido',
            field=models.PositiveIntegerField(default=0, help_text='Días estimados de entrega cuando el equipo es sobre pedido (0 = usar el general del sitio).'),
        ),
    ]
