# Generated by Django 5.2.9 on 2026-08-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0036_configuracionsitio_dias_entrega_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='permite_sobre_pedido',
            field=models.BooleanField(default=False, help_text='Permite vender este producto aunque no haya unidades disponibles en bodega.'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='cotizacion_condiciones_renta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='datos_bancarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='dias_entrega_pedido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='negocio_representante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_principal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_respaldos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='correoaviso',
            name='etiqueta',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-1)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='dias_entrega_pedido',
            field=models.PositiveIntegerField(default=0, help_text='Días estimados de entrega cuando se vende sobre pedido (0 = usar el general del sitio).'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='obracliente',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fiscal_regimen',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fiscal_uso_cfdi',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='obra_direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='obra_responsable',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.CreateModel(
            name='ConversacionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('asunto', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('last_read_admin', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación (soporte)',
                'verbose_name_plural': 'Conversaciones (soporte)',
                'db_table': 'conversaciones_soporte',
                'ordering': ['-actualizada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_tipo', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], max_length=20)),
                ('cuerpo', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('autor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_soporte', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='maquinaria.conversacionsoporte')),
            ],
            options={
                'verbose_name': 'Mensaje (soporte)',
                'verbose_name_plural': 'Mensajes (soporte)',
                'db_table': 'mensajes_soporte',
                'ordering': ['creada', 'id'],
            },
        ),
    ]
