# Generated by Django 5.2.9 on 2026-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0037_equipo_permite_sobre_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='El cliente ya terminó la guía de primer uso.'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_pasos_completados',
            field=models.JSONField(blank=True, default=list, help_text='IDs de los pasos o tours que el cliente ya completó.'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Versión del tour. Al incrementar, se obliga a ver la nueva guía.'),
        ),
    ]
