# Generated by Django 5.2.9 on 2026-08-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0039_onboarding_solo_nuevos'),
    ]

    operations = [
        migrations.AddField(
            model_name='obracliente',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
