# Generated by Django 5.2.9 on 2026-08-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0043_rol_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='codigo_ajuste',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='descuento_contado_pct',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
