# Generated by Django 5.2.9 on 2026-08-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0044_configuracionsitio_codigo_ajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='anticipo_minimo_pct',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
