# Generated by Django 5.2.9 on 2026-08-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0045_configuracionsitio_anticipo_minimo_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cupon',
            name='usado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
