# Generated by Django 5.2.9 on 2026-08-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0046_cupon_usado_cupon_usado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_seguridad',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
    ]
