# Generated by Django 5.2.17 on 2026-08-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0047_perfilusuario_codigo_bloqueado_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_token_creado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
