# Generated by Django 5.2.17 on 2026-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0048_perfilusuario_email_token_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(default=3, help_text='Meses de garantía al comprador. 0 = se vende sin garantía.'),
        ),
    ]
