# Generated by Django 5.2.17 on 2026-08-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0049_equipo_garantia_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='caja_renta_maquinaria',
            field=models.BooleanField(default=False, help_text='Permite levantar rentas desde la caja del mostrador.'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='caja_vende_maquinaria',
            field=models.BooleanField(default=False, help_text='Permite vender unidades de maquinaria desde la caja del mostrador.'),
        ),
    ]
