# Generated by Django 5.2.17 on 2026-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0050_configuracionsitio_caja_renta_maquinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_codigo_barras',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_lema',
            field=models.CharField(blank=True, default='Renta · Venta · Servicio', max_length=80),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_leyenda',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_logo_escala',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_mostrar_direccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_mostrar_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_mostrar_rfc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_mostrar_telefono',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_mostrar_web',
            field=models.BooleanField(default=False),
        ),
    ]
