# Generated by Django 5.2.17 on 2026-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0051_configuracionsitio_ticket_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='ticket_logo_origen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
