# Generated by Django 5.2.17 on 2026-08-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0052_configuracionsitio_ticket_logo_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPrecioLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=20)),
                ('anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rol', models.CharField(blank=True, default='', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_precio', to='maquinaria.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de precio de lista',
                'verbose_name_plural': 'Cambios de precio de lista',
                'db_table': 'cambio_precio_lista',
                'ordering': ['-creado_en'],
            },
        ),
    ]
