# Generated by Django 5.2.17 on 2026-08-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0053_cambiopreciolista'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='caja_cobra_abonos',
            field=models.BooleanField(default=False, help_text='Permite recibir abonos de pedidos y rentas desde la caja del mostrador.'),
        ),
    ]
