# Generated by Django 5.2.17 on 2026-08-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0054_caja_cobra_abonos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
                ('capacidad', models.CharField(max_length=40)),
                ('anterior', models.BooleanField(blank=True, null=True)),
                ('nuevo', models.BooleanField(blank=True, null=True)),
                ('rol_usuario', models.CharField(blank=True, default='', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_permiso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de permiso',
                'verbose_name_plural': 'Cambios de permisos',
                'db_table': 'cambio_permiso_rol',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
                ('capacidad', models.CharField(max_length=40)),
                ('permitido', models.BooleanField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso por rol',
                'verbose_name_plural': 'Permisos por rol',
                'db_table': 'permiso_rol',
                'ordering': ['rol', 'capacidad'],
                'unique_together': {('rol', 'capacidad')},
            },
        ),
    ]
