# Generated by Django 5.2.17 on 2026-08-24 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0055_cambiopermisorol_permisorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiopermisorol',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cambiopermisorol',
            name='capacidad',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='cambiopermisorol',
            name='rol',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='permisorol',
            name='rol',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('protegido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['-nivel', 'nombre'],
            },
        ),
    ]
