# Generated by Django 5.2.17 on 2026-08-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0057_siembra_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='factura_color',
            field=models.CharField(blank=True, default='', help_text='Color de acento de la factura en PDF (#RRGGBB). Vacío = el dorado de la casa.', max_length=7),
        ),
    ]
