# Generated by Django 5.2.17 on 2026-08-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0058_configuracionsitio_factura_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='factura_color',
        ),
    ]
