# Generated by Django 5.2.17 on 2026-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0059_remove_configuracionsitio_factura_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='renta_liquidacion_minima_pct',
            field=models.PositiveSmallIntegerField(default=75),
        ),
    ]
