# Generated by Django 5.2.17 on 2026-09-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0060_configuracionsitio_renta_liquidacion_minima_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email_token_creado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_otp',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_otp_bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_otp_creado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='email_otp_intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
