# Generated by Django 5.2.17 on 2026-09-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0061_remove_perfilusuario_email_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='aviso_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='aviso_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='aviso_liga',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='aviso_liga_texto',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='aviso_texto',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
