# Generated by Django 5.2.17 on 2026-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0062_configuracionsitio_aviso_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bienvenida_enviada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
